apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "airflow.fullname" . }}-env"
data:
  POSTGRES_HOST: "{{ template "airflow.postgresql.fullname" . }}"
  POSTGRES_DB: "{{ .Values.postgresql.postgresDatabase }}"
  POSTGRES_USER: "{{ .Values.postgresql.postgresUser }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresPassword }}"
  REDIS_HOST: "{{ template "airflow.redis.fullname" . }}"
  REDIS_PASSWORD: "{{ .Values.redis.redisPassword }}"
  FLOWER_PORT: "5555"
  AIRFLOW__WEBSERVER__BASE_URL: "http://localhost:8080{{ .Values.airflow.url_prefix }}"
  # Note: changing `Values.airflow.config` won't change the configmap checksum and so won't make
  # the pods to restart
  {{- range $setting, $option := .Values.airflow.config }}
  {{ $setting }}: "{{ $option }}"
  {{- end }}
