airflow:
  image:
    repository: puckel/docker-airflow
    tag: 1.10.0-4
    pull_policy: IfNotPresent
  service:
    type: NodePort
  web_replicas: 1
  config:
    AIRFLOW__CORE__LOGGING_LEVEL: DEBUG
    AIRFLOW__CORE__LOAD_EXAMPLES: True

workers:
  serviceAccountName: "default"
  replicas: 1
  celery:
    instances: 1

ingress:
  enabled: true
  web:
    path: "/airflow"
    host: "minikube"
    annotations:
      traefik.frontend.rule.type: PathPrefix
      kubernetes.io/ingress.class: traefik
  flower:
    path: "/airflow/flower"
    host: "minikube"
    annotations:
      traefik.frontend.rule.type: PathPrefixStrip
      kubernetes.io/ingress.class: traefik

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
